version: '3'

services:

  ## HYPOTESIS DJANGO
  hypotesis_django:
    build: hypotesis_django/.
    container_name: hypotesis_django
    image: hypotesis_django:latest
    working_dir: ${HYP_DJANGO_WORKDIR}
    env_file:
      - hypotesis_django/.env
    depends_on:
      - hypotesis_db

  ## HYPOTESIS PRO
  hypotesis_pro:
    build: hypotesis_pro/.
    container_name: hypotesis_pro
    image: hypotesis_pro:latest
    working_dir: ${HYP_PRO_WORKDIR_BUILD}
    environment:
      - NODE_ENV=production
      - HYP_MANAGER_URL=${HYP_MANAGER_SERVER}:${HYP_MANAGER_PORT}
    env_file:
      - hypotesis_pro/.env
    ports:
      - ${HYP_PRO_PORT}:${HYP_PRO_PORT}
    volumes:
      - ./hypotesis_pro/nginx.conf:/etc/nginx/nginx.conf
      - ./hypotesis_pro/default.conf:/etc/nginx/conf.d/default.conf
    stdin_open: true
    tty: true
    #depends_on:
    #  - hypotesis_manager
    # - hypotesis_context
    # - hypotesis_enrol
    # - hypotesis_item

  ## HYPOTESIS MANAGER
  hypotesis_manager:
    restart: always
    build: hypotesis_manager/.
    container_name: hypotesis_manager
    image: hypotesis_manager:latest
    working_dir: ${HYP_MANAGER_WORKDIR}
    env_file:
      - hypotesis_manager/.env
    environment:
      - HYP_LOCAL_IP=${HYP_LOCAL_IP}
      - URL_PORT=${HYP_MANAGER_SERVER}:${HYP_MANAGER_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - HYP_DB_IP=${HYP_DB_IP}
      - HYP_DB_PORT=${HYP_DB_PORT}
      - HYP_MANAGER_SUPER_USER=${HYP_MANAGER_SUPER_USER}
      - HYP_MANAGER_SUPER_USER_EMAIL=${HYP_MANAGER_SUPER_USER_EMAIL}
      - HYP_MANAGER_SUPER_USER_PASS=${HYP_MANAGER_SUPER_USER_PASS}
    ports:
      - ${HYP_MANAGER_PORT}:${HYP_MANAGER_PORT}
    volumes:
      - ./hypotesis_manager:${HYP_MANAGER_WORKDIR}
    stdin_open: true
    tty: true
    networks:
      hypotesis_vpc:
        ipv4_address: ${HYP_MANAGER_IP}
    depends_on:
      - hypotesis_django
      - hypotesis_db

  ## HYPOTESIS CONTEXT
  hypotesis_context:
    restart: always
    build: hypotesis_context/.
    container_name: hypotesis_context
    image: hypotesis_context:latest
    working_dir: ${HYP_CONTEXT_WORKDIR}
    env_file:
      - hypotesis_context/.env
    environment:
      - HYP_LOCAL_IP=${HYP_LOCAL_IP}
      - URL_PORT=${HYP_CONTEXT_SERVER}:${HYP_CONTEXT_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - HYP_DB_IP=${HYP_DB_IP}
      - HYP_DB_PORT=${HYP_DB_PORT}
      - HYP_CONTEXT_SUPER_USER=${HYP_CONTEXT_SUPER_USER}
      - HYP_CONTEXT_SUPER_USER_EMAIL=${HYP_CONTEXT_SUPER_USER_EMAIL}
      - HYP_CONTEXT_SUPER_USER_PASS=${HYP_CONTEXT_SUPER_USER_PASS}
    ports:
      - ${HYP_CONTEXT_PORT}:${HYP_CONTEXT_PORT}
    volumes:
      - ./hypotesis_context:${HYP_CONTEXT_WORKDIR}
    stdin_open: true
    tty: true
    networks:
      hypotesis_vpc:
        ipv4_address: ${HYP_CONTEXT_IP}
    depends_on:
      - hypotesis_django
      - hypotesis_db

  ## HYPOTESIS ENROL
  hypotesis_enrol:
    restart: always
    build: hypotesis_enrol/.
    container_name: hypotesis_enrol
    image: hypotesis_enrol:latest
    working_dir: ${HYP_ENROL_WORKDIR}
    env_file:
      - hypotesis_enrol/.env
    environment:
      - HYP_LOCAL_IP=${HYP_LOCAL_IP}
      - URL_PORT=${HYP_ENROL_SERVER}:${HYP_ENROL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - HYP_DB_IP=${HYP_DB_IP}
      - HYP_DB_PORT=${HYP_DB_PORT}
      - HYP_ENROL_SUPER_USER=${HYP_ENROL_SUPER_USER}
      - HYP_ENROL_SUPER_USER_EMAIL=${HYP_ENROL_SUPER_USER_EMAIL}
      - HYP_ENROL_SUPER_USER_PASS=${HYP_ENROL_SUPER_USER_PASS}
    ports:
      - ${HYP_ENROL_PORT}:${HYP_ENROL_PORT}
    volumes:
      - ./hypotesis_enrol:${HYP_ENROL_WORKDIR}
    stdin_open: true
    tty: true
    networks:
      hypotesis_vpc:
        ipv4_address: ${HYP_ENROL_IP}
    depends_on:
      - hypotesis_django
      - hypotesis_db

  ## HYPOTESIS ITEM
  hypotesis_item:
    restart: always
    build: hypotesis_item/.
    container_name: hypotesis_item
    image: hypotesis_item:latest
    working_dir: ${HYP_ITEM_WORKDIR}
    env_file:
      - hypotesis_item/.env
    environment:
      - HYP_LOCAL_IP=${HYP_LOCAL_IP}
      - URL_PORT=${HYP_ITEM_SERVER}:${HYP_ITEM_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - HYP_DB_IP=${HYP_DB_IP}
      - HYP_DB_PORT=${HYP_DB_PORT}
      - HYP_ITEM_SUPER_USER=${HYP_ITEM_SUPER_USER}
      - HYP_ITEM_SUPER_USER_EMAIL=${HYP_ITEM_SUPER_USER_EMAIL}
      - HYP_ITEM_SUPER_USER_PASS=${HYP_ITEM_SUPER_USER_PASS}
    ports:
      - ${HYP_ITEM_PORT}:${HYP_ITEM_PORT}
    volumes:
      - ./hypotesis_item:${HYP_ITEM_WORKDIR}
    stdin_open: true
    tty: true
    networks:
      hypotesis_vpc:
        ipv4_address: ${HYP_ITEM_IP}
    depends_on:
      - hypotesis_django
      - hypotesis_db

  ## HYPOTESIS DB
  hypotesis_db:
    build: hypotesis_db/.
    container_name: hypotesis_db
    image: hypotesis_db:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=hypotesis
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - ${HYP_DB_PORT}
    ports:
      - ${HYP_DB_PORT}:${HYP_DB_PORT}
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./docker/provision/hypotesis_db:/docker-entrypoint-initdb.d
    networks:
      hypotesis_vpc:
        ipv4_address: ${HYP_DB_IP}

networks:
  hypotesis_vpc:
    ipam:
      config:
        - subnet: ${HYP_VPC_RANGE}