# Generated by Django 3.0.6 on 2020-06-01 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('alias', models.CharField(error_messages={'unique': 'A state of enrol with that alias already exists.'}, max_length=20, primary_key=True, serialize=False, verbose_name='alias')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='EnrolContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='name')),
                ('context', models.CharField(max_length=100, verbose_name='name')),
                ('role', models.CharField(max_length=100, verbose_name='name')),
                ('state_at', models.DateTimeField(blank=True, null=True, verbose_name='state at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrol.State', verbose_name='state')),
            ],
        ),
    ]
