# Generated by Django 3.0.6 on 2020-06-01 20:52

from django.db import migrations


# Add States.
def add_states(apps, schema_editor):
    state = apps.get_model('enrol', 'State')
    state_object = state(name='Activo', alias='active')
    state_object.save()
    state_object = state(name='Deshabilitado', alias='unactive')
    state_object.save()
    state_object = state(name='Terminado', alias='finished')
    state_object.save()
    state_object = state(name='Pausado', alias='paused')
    state_object.save()
    state_object = state(name='En creación', alias='creating')
    state_object.save()


# Add Enrol Context.
def add_enrol_context(apps, schema_editor):
    state = apps.get_model('enrol', 'State')
    state_active = state.objects.get(alias='active')
    enrolcontext = apps.get_model('enrol', 'EnrolContext')
    enrolcontext_object = enrolcontext(user='amanzanod', context='dgbd_aula1', role='student', state=state_active)
    enrolcontext_object.save()
    enrolcontext_object = enrolcontext(user='amanzanod', context='dgbd', role='student', state=state_active)
    enrolcontext_object.save()
    enrolcontext_object = enrolcontext(user='amanzanod', context='cicj', role='student', state=state_active)
    enrolcontext_object.save()
    enrolcontext_object = enrolcontext(user='mamaga', context='dgbd_aula1', role='student', state=state_active)
    enrolcontext_object.save()
    enrolcontext_object = enrolcontext(user='rogoag', context='dgbd_aula1', role='student', state=state_active)
    enrolcontext_object.save()
    enrolcontext_object = enrolcontext(user='jusagu', context='dgbd_aula1', role='teacherpro', state=state_active)
    enrolcontext_object.save()
    enrolcontext_object = enrolcontext(user='jugamo', context='dgbd_aula1', role='author', state=state_active)
    enrolcontext_object.save()
    enrolcontext_object = enrolcontext(user='dapisa', context='dgbd_aula1', role='student', state=state_active)
    enrolcontext_object.save()
    enrolcontext_object = enrolcontext(user='sijiso', context='dgbd_aula1', role='student', state=state_active)
    enrolcontext_object.save()
    enrolcontext_object = enrolcontext(user='magaro', context='dgbd_aula1', role='student', state=state_active)
    enrolcontext_object.save()
    enrolcontext_object = enrolcontext(user='jomose', context='dgbd_aula1', role='student', state=state_active)
    enrolcontext_object.save()
    enrolcontext_object = enrolcontext(user='tallome', context='dgbd_aula1', role='student', state=state_active)
    enrolcontext_object.save()


class Migration(migrations.Migration):

    dependencies = [
        ('enrol', '0002_enrolcontext_state'),
    ]

    operations = [
        migrations.RunPython(add_states),
        migrations.RunPython(add_enrol_context),
    ]
