const HYPOTESIS_MANAGER_URL = 'http://192.168.99.100:8000/api/';
const HYP_MANAGER_USER = HYPOTESIS_MANAGER_URL + 'user/';
const HYP_MANAGER_ROLE = HYPOTESIS_MANAGER_URL + 'role/';

export { HYP_MANAGER_USER, HYP_MANAGER_ROLE};
