const HYPOTESIS_MANAGER_URL = 'http://127.0.0.1:8000/api/';
const HYP_MANAGER_USER = HYPOTESIS_MANAGER_URL + 'user/';
const HYP_MANAGER_ROLE = HYPOTESIS_MANAGER_URL + 'role/';
const HYP_MANAGER_PROVINCE = HYPOTESIS_MANAGER_URL + 'province/';
const HYP_MANAGER_COUNTRY = HYPOTESIS_MANAGER_URL + 'country/';
const HYP_MANAGER_STATE = HYPOTESIS_MANAGER_URL + 'state/';
const HYP_MANAGER_LANGUAGE = HYPOTESIS_MANAGER_URL + 'language/';
const HYP_MANAGER_PERMISSION = HYPOTESIS_MANAGER_URL + 'permission/';
const HYP_MANAGER_CONTEXT= HYPOTESIS_MANAGER_URL + 'context/';
const HYP_MANAGER_CREATE_USER= HYPOTESIS_MANAGER_URL + 'user_manage';


const HYPOTESIS_CONTEXT_URL = 'http://192.168.99.100:8001/api/';
const HYP_MANAGER_GRADE= HYPOTESIS_CONTEXT_URL + 'grade/';

export {
    HYP_MANAGER_USER,
    HYP_MANAGER_ROLE,
    HYP_MANAGER_PERMISSION,
    HYP_MANAGER_CONTEXT,
    HYP_MANAGER_PROVINCE,
    HYP_MANAGER_COUNTRY,
    HYP_MANAGER_STATE,
    HYP_MANAGER_LANGUAGE,
    HYP_MANAGER_GRADE,
    HYP_MANAGER_CREATE_USER
};
