# Generated by Django 3.0.6 on 2020-05-21 12:34

from django.db import migrations, models
from django.contrib.auth.models import User  # where User lives
import os


def forwards_func(apps, schema_editor):
    admin_username = os.environ.get('HYP_CONTEXT_SUPER_USER', 'admin')
    admin_email = os.environ.get('HYP_CONTEXT_SUPER_USER_EMAIL', '')
    admin_pass = os.environ.get('HYP_CONTEXT_SUPER_USER_PASS', '1234')

    try:
        User.objects.create_superuser(admin_username, email=admin_email, password=admin_pass)
    except Exception as e:
        print(str(e))


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
