# Generated by Django 3.0.6 on 2020-05-24 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible_at', models.DateTimeField(blank=True, null=True)),
                ('state_at', models.DateTimeField(blank=True, null=True)),
                ('alias', models.CharField(error_messages={'unique': 'A category with that alias already exists.'}, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('is_visible', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContextType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(error_messages={'unique': 'A type of context with that alias already exists.'}, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(error_messages={'unique': 'A format of context with that alias already exists.'}, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(error_messages={'unique': 'A language of context with that alias already exists.'}, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(error_messages={'unique': 'A level of context with that alias already exists.'}, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(error_messages={'unique': 'A state of context with that alias already exists.'}, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible_at', models.DateTimeField(blank=True, null=True)),
                ('state_at', models.DateTimeField(blank=True, null=True)),
                ('alias', models.CharField(error_messages={'unique': 'A context of this type with that alias already exists.'}, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('syllabus', models.TextField(blank=True, max_length=500, null=True)),
                ('requeriments', models.TextField(blank=True, max_length=500, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('tech_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher_main', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Category')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.Format')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.Language')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Level')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Context')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.State')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.ContextType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='context_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='context.ContextType'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='context.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='context.State'),
        ),
    ]
