# Generated by Django 3.0.6 on 2020-05-27 20:25

from django.db import migrations


# Add Courses.
def add_courses(apps, schema_editor):
    context_type = apps.get_model('context', 'ContextType')
    context_type_course = context_type.objects.get(alias='course')
    state = apps.get_model('context', 'State')
    state_active = state.objects.get(alias='active')
    state_finished = state.objects.get(alias='finished')
    state_paused = state.objects.get(alias='paused')
    state_creating = state.objects.get(alias='creating')
    language = apps.get_model('context', 'Language')
    language_es = language.objects.get(code='es')
    level = apps.get_model('context', 'Level')
    level_begin = level.objects.get(alias='beginner')
    level_medium = level.objects.get(alias='medium')
    level_advanced = level.objects.get(alias='advanced')
    category = apps.get_model('context', 'Category')
    category_python = category.objects.get(alias='python')
    category_moodle = category.objects.get(alias='moodle')
    category_deploy = category.objects.get(alias='deploy')
    category_postman = category.objects.get(alias='postman')
    category_php = category.objects.get(alias='php')
    category_docker = category.objects.get(alias='docker')
    category_aws = category.objects.get(alias='aws')
    category_html = category.objects.get(alias='html5')
    category_ux = category.objects.get(alias='ux')
    context = apps.get_model('context', 'Context')
    course_object = context(name='Curso básico de Django 3 con Python', alias='dgbd', state=state_active,
                            is_visible=True, type=context_type_course, language=language_es,
                            category=category_python, level=level_begin, )
    course_object.save()
    course_object = context(name='Curso avanzado de Moodle para Desarrolladores', alias='camd', state=state_active,
                            is_visible=True, type=context_type_course, language=language_es,
                            category=category_moodle, level=level_advanced, )
    course_object.save()
    course_object = context(name='Curso de integración continua con Jenkins', alias='cicj', state=state_active,
                            is_visible=True, type=context_type_course, language=language_es,
                            category=category_deploy, level=level_medium, )
    course_object.save()
    course_object = context(name='Curso avanzado de ciberseguridad en PHP', alias='sgphp', state=state_paused,
                            is_visible=True, type=context_type_course, language=language_es,
                            category=category_php, level=level_advanced, )
    course_object.save()
    course_object = context(name='Creación de contenedores con Docker', alias='dock', state=state_active,
                            is_visible=False, type=context_type_course, language=language_es,
                            category=category_docker, level=level_advanced, )
    course_object.save()
    course_object = context(name='Maquetación web con HTML5 y CSS3', alias='htcss', state=state_creating,
                            is_visible=True, type=context_type_course, language=language_es,
                            category=category_html, level=level_begin, )
    course_object.save()
    course_object = context(name='Diseño web con Adobe XD avanzado', alias='xdavz', state=state_finished,
                            is_visible=True, type=context_type_course, language=language_es,
                            category=category_ux, level=level_advanced, )
    course_object.save()
    course_object = context(name='Aprenda a manejar Postman como un experto', alias='apostc', state=state_finished,
                            is_visible=True, type=context_type_course, language=language_es,
                            category=category_postman, level=level_advanced, )
    course_object.save()
    course_object = context(name='Creación de instancias y redes en AWS', alias='arawsc', state=state_finished,
                            is_visible=True, type=context_type_course, language=language_es,
                            category=category_aws, level=level_medium, )
    course_object.save()
    course_object = context(name='Aplicaciones con Laravel y Vue 3', alias='larvu', state=state_finished,
                            is_visible=True, type=context_type_course, language=language_es,
                            category=category_php, level=level_begin, )
    course_object.save()


# Add Class Rooms.
def add_classrooms(apps, schema_editor):
    context_type = apps.get_model('context', 'ContextType')
    context_type_class = context_type.objects.get(alias='classroom')
    state = apps.get_model('context', 'State')
    state_active = state.objects.get(alias='active')
    language = apps.get_model('context', 'Language')
    language_es = language.objects.get(code='es')
    context = apps.get_model('context', 'Context')
    course_dgbd = context.objects.get(alias='dgbd')
    course_htcss = context.objects.get(alias='htcss')
    course_apost = context.objects.get(alias='apostc')
    course_sgphp = context.objects.get(alias='sgphp')
    course_dock = context.objects.get(alias='dock')
    course_araws = context.objects.get(alias='arawsc')
    course_camd = context.objects.get(alias='camd')
    course_xdavz = context.objects.get(alias='xdavz')
    class_object = context(name='Aula 1', alias='dgbd_aula1', state=state_active, is_visible=True,
                           type=context_type_class, language=language_es, parent=course_dgbd)
    class_object.save()
    class_object = context(name='Aula 2', alias='dgbd_aula2', state=state_active, is_visible=True,
                           type=context_type_class, language=language_es, parent=course_dgbd)
    class_object.save()
    class_object = context(name='Clase A', alias='htcss_clasea', state=state_active, is_visible=True,
                           type=context_type_class, language=language_es, parent=course_htcss)
    class_object.save()
    class_object = context(name='Aula 1', alias='apostc_clasea', state=state_active, is_visible=True,
                           type=context_type_class, language=language_es, parent=course_apost)
    class_object.save()
    class_object = context(name='Lions', alias='sgphp_lions', state=state_active, is_visible=True,
                           type=context_type_class, language=language_es, parent=course_sgphp)
    class_object.save()
    class_object = context(name='Aula 1', alias='dock_aula1', state=state_active, is_visible=False,
                           type=context_type_class, language=language_es, parent=course_dock)
    class_object.save()
    class_object = context(name='Tigers', alias='arawsc_tigers', state=state_active, is_visible=True,
                           type=context_type_class, language=language_es, parent=course_araws)
    class_object.save()
    class_object = context(name='2º E', alias='camd_2e', state=state_active, is_visible=True,
                           type=context_type_class, language=language_es, parent=course_camd)
    class_object.save()
    class_object = context(name='Aula 1', alias='xdavz_aula1', state=state_active, is_visible=True,
                           type=context_type_class, language=language_es, parent=course_xdavz)
    class_object.save()
    class_object = context(name='Aula X', alias='xdavz_aulax', state=state_active, is_visible=True,
                           type=context_type_class, language=language_es, parent=course_xdavz)
    class_object.save()


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0003_auto_20200527_1838'),
    ]

    operations = [
        migrations.RunPython(add_courses),
        migrations.RunPython(add_classrooms),
    ]
