# Generated by Django 3.0.6 on 2020-06-01 18:37

from django.db import migrations


# Add Item Types.
def add_item_types(apps, schema_editor):
    context_type = apps.get_model('item', 'ItemType')
    context_type_object = context_type(name='Entregable', alias='deliverable', type='activity')
    context_type_object.save()
    context_type_object = context_type(name='Cuestionario', alias='question', type='activity')
    context_type_object.save()
    context_type_object = context_type(name='SCORM', alias='scorm', type='activity')
    context_type_object.save()
    context_type_object = context_type(name='H5P', alias='h5p', type='activity')
    context_type_object.save()
    context_type_object = context_type(name='Debate', alias='debate', type='activity')
    context_type_object.save()
    context_type_object = context_type(name='Video', alias='video', type='resource')
    context_type_object.save()
    context_type_object = context_type(name='Audio', alias='audio', type='resource')
    context_type_object.save()
    context_type_object = context_type(name='Documento PDF', alias='pdf_file', type='resource')
    context_type_object.save()
    context_type_object = context_type(name='Videoconferencia', alias='conference', type='resource')
    context_type_object.save()
    context_type_object = context_type(name='HTML', alias='html', type='resource')
    context_type_object.save()


# Add Format.
def add_format(apps, schema_editor):
    format_context = apps.get_model('item', 'Format')
    format_object = format_context(name='Individual', alias='individual')
    format_object.save()
    format_object = format_context(name='Grupo', alias='group')
    format_object.save()
    format_object = format_context(name='Gran Grupo', alias='grandgroup')
    format_object.save()


# Add States.
def add_states(apps, schema_editor):
    state = apps.get_model('item', 'State')
    state_object = state(name='Activo', alias='active')
    state_object.save()
    state_object = state(name='Deshabilitado', alias='unactive')
    state_object.save()
    state_object = state(name='Terminado', alias='finished')
    state_object.save()
    state_object = state(name='En creación', alias='creating')
    state_object.save()


# Add Levels.
def add_levels(apps, schema_editor):
    level = apps.get_model('item', 'Level')
    level_object = level(name='Principiante', alias='beginner')
    level_object.save()
    level_object = level(name='Medio', alias='medium')
    level_object.save()
    level_object = level(name='Avanzado', alias='advanced')
    level_object.save()
    level_object = level(name='Experto', alias='expert')
    level_object.save()
    level_object = level(name='Profesional', alias='professional')
    level_object.save()


# Add Languages.
def add_languages(apps, schema_editor):
    language = apps.get_model('item', 'Language')
    language_object = language(code='es', name='Español')
    language_object.save()
    language_object = language(code='en', name='Inglés')
    language_object.save()


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_format_item_itemtype_language_level_section_state'),
    ]

    operations = [
        migrations.RunPython(add_item_types),
        migrations.RunPython(add_format),
        migrations.RunPython(add_states),
        migrations.RunPython(add_levels),
        migrations.RunPython(add_languages),
    ]


