# Generated by Django 3.0.6 on 2020-05-22 13:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.SmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=False)),
                ('alias', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('alias', models.CharField(max_length=20, unique=True)),
                ('state', models.SmallIntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('syllabus', models.TextField(blank=True, max_length=500, null=True)),
                ('requeriments', models.TextField(blank=True, max_length=500, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('tech_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher_main', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('alias', models.CharField(max_length=20, unique=True)),
                ('state', models.SmallIntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('syllabus', models.TextField(blank=True, max_length=500, null=True)),
                ('requeriments', models.TextField(blank=True, max_length=500, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('tech_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher_main', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Category')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='context.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('alias', models.CharField(max_length=20, unique=True)),
                ('state', models.SmallIntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('syllabus', models.TextField(blank=True, max_length=500, null=True)),
                ('requeriments', models.TextField(blank=True, max_length=500, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('tech_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher_main', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('alias', models.CharField(max_length=20, unique=True)),
                ('state', models.SmallIntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('syllabus', models.TextField(blank=True, max_length=500, null=True)),
                ('requeriments', models.TextField(blank=True, max_length=500, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('tech_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher_main', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=20)),
                ('context_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('type', 'context_id')},
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('alias', models.CharField(max_length=20, unique=True)),
                ('state', models.SmallIntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('syllabus', models.TextField(blank=True, max_length=500, null=True)),
                ('requeriments', models.TextField(blank=True, max_length=500, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('tech_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher_main', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Category')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='context.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='context.Context'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='context.Category'),
        ),
    ]
